### ISSUE TITLE
Issues running bot immediately after configuration

### ISSUE THREAD

**Issue by cameronpants** [peteloh/DFK-routine-runner#2]
After configuring the bot for the first time and running it, I'm running into this error no matter what I try:

![image](https://user-images.githubusercontent.com/48197620/166134319-4b0cb1cc-9e92-4722-ac3b-3763cbf5eb54.png)

I thought the issue was related to the heroes in the config already being listed for sale so I de-listed them, attempted to run the bot again, same issue. I'm unsure if the issue is something on my end or if there's a problem with the code. Let me know if any more info is needed!

**Comment by peteloh** [comment]
I'm sorry, I think the config file for this public repo was wrong, I'm going to update my current version of the code now. Also this code only supports the level 0 quests only (fishing, foraging, mining, gardening), it seems like dfk have created a new contract for the level 1 stats quests so I will need to look into it before implementing.

**Comment by cameronpants** [comment]
No problem at all, thanks so much for the update, pete!

**Comment by cameronpants** [comment]
Hey Pete, still running into some issues unfortunately. Upon testing the bot with the updated code, I'm getting this error relating to the auction system now:

![image](https://user-images.githubusercontent.com/48197620/166866460-7005d9e9-1e86-4209-b204-531c40f0e724.png)

Let me know if you need any more info relating to the issue, appreciate all your work!

**Comment by peteloh** [comment]
Hi 
This seems to be related to the "heroes" section in the config.json file. Below is what is what the format should be like:
the hero contains another nested json object that consists of heroId as the key, and another nested object of forsale and the price you want to list your hero. "forSale": false is when you dont want to list your hero and true when you want to put them on auction.

From your screenshot it seems like the code couldnt find neither true nor false for the heroId it found. If putting your heros in the format below doesnt work maybe you can try sending me your config file. I hope you find it useful!


![Screenshot_20220505-081514.png](https://user-images.githubusercontent.com/72593938/166877676-11095aa6-172b-4684-b9d6-739016593696.png)

**Comment by cameronpants** [comment]
Sorry about that, should've included the config file to start with haha. See below for the heroes auction section of the config, let me know if you need the entire config file itself and I'll send that over!

![image](https://user-images.githubusercontent.com/48197620/166963853-f8d27a4c-7ac0-486e-8765-f36d74b66863.png)

**Comment by peteloh** [comment]
That looks fine to me, I've ran the exact same code and I had no problem listing my heroes as shown below 
![image](https://user-images.githubusercontent.com/72593938/167012871-c3e12a8e-9d3a-44f7-8ed8-503410beec43.png)

A possible problem is that you might have not listed all your questing heroes under the "heroes" key?, the idea for the code is that it checks all the heroId you put into the "quests" section to see which quest each hero should do when there is enough stamina and when the heroes are regenerating stamina, it will check if you want it forSale and the listing price for that heroId under the "heroes" section of config.  This means that you need every heroId that is in "quests" section to also be under the "heroes" section, if you dont want to list that for sale you just need to write "forsale": false.

If this does not fix it please send me the whole config file (maybe take out your wallet address for privacy),  thanks.

**Comment by cameronpants** [comment]
Ah, that fixed it! Sorry about that, I wasn't aware all questing heroes needed to also be listed under the auction section even if they weren't for sale. Thank you very much for helping me out with this :)

One last small thing I wanted to ask though, is it possible to adjust the default starting stamina for JEWEL mining from 15 to 20 and if so, would that be done by adjusting line 221 (minStamina = 25;) in routine_runner.js to 20, or somewhere else? Appreciate all your amazing work once again!

**Comment by cameronpants** [comment]
Sorry, one more thing to add... After running the bot for a couple hours, I noticed it's not starting non-professional quests automatically despite some heroes having enough stamina to do so. In config.json under the Foraging quest section, I tried setting `"professional": true,` to `"false"` but unfortunately the issue still occurs despite the heroes having full stamina. I attached my config just in-case you want to take a look, let me know if you need any additional info!

[configgithub.txt](https://github.com/peteloh/DFK-routine-runner/files/8636398/configgithub.txt)

**Comment by peteloh** [comment]
> Ah, that fixed it! Sorry about that, I wasn't aware all questing heroes needed to also be listed under the auction section even if they weren't for sale. Thank you very much for helping me out with this :)
> 
> One last small thing I wanted to ask though, is it possible to adjust the default starting stamina for JEWEL mining from 15 to 20 and if so, would that be done by adjusting line 221 (minStamina = 25;) in routine_runner.js to 20, or somewhere else? Appreciate all your amazing work once again!

thats right, ive added minstamina value in the config file now

**Comment by peteloh** [comment]
> 

I'm sorry about this but I will have to check this again as I've never tested the non-professional part of the code as I've always let my hero do what they are good at - I will let you know when Ive look into it. A good news is that ive added the level 1 training quests now, you should be able to assign the heroes to do those quests professionally instead (since its always 5 stamina) which will likely give a higher xp efficiency. (unless you want the professional items, in that case you unfortunately have to manually do those quests first).

**Comment by peteloh** [comment]
> Sorry, one more thing to add... After running the bot for a couple hours, I noticed it's not starting non-professional quests automatically despite some heroes having enough stamina to do so. In config.json under the Foraging quest section, I tried setting `"professional": true,` to `"false"` but unfortunately the issue still occurs despite the heroes having full stamina. I attached my config just in-case you want to take a look, let me know if you need any additional info!
> 
> [configgithub.txt](https://github.com/peteloh/DFK-routine-runner/files/8636398/configgithub.txt)

I'm sorry about this but I will have to check this again as I've never tested the non-professional part of the code as I've always let my hero do what they are good at - I will let you know when Ive look into it. A good news is that ive added the level 1 training quests now, you should be able to assign the heroes to do those quests professionally instead (since its always 5 stamina) which will likely give a higher xp efficiency. (unless you want the professional items, in that case you unfortunately have to manually do those quests first).

**Comment by cameronpants** [comment]
Awesome, thanks so much for pushing out that minstamina update and looking into all of this! Truly appreciated :)

**Comment by peteloh** [comment]
> Awesome, thanks so much for pushing out that minstamina update and looking into all of this! Truly appreciated :)

i've pushed it on the config but forgot to assign to the minstamina value in the code so it became `undefined` lol, ive pushed the most recent update to fix this.
